config/routes.rb
Rails.application.routes.draw do
get 'trips/show' => 'trips#show'
 

  root 'trips#new'

end

app/models/gas_station.rb
class GasStation
	attr_accessor :name, :price, :city, :distance, :address
	def initialize(name, price, city, distance, address)
		@name = name
		@price = price
		@city =city
		@distance = distance
		@address = address
	end


end

app/models/place.rb
class Place
	attr_accessor :address, :latitude, :longitude
	def initialize(address)
		@address = address
		result = Geocoder.coordinates(address)
		@latitude = result[0]
		@longitude = result[1]
	end
end

app/models/trip.rb
class Trip
	require 'gas_station'
	attr_accessor :name, :start, :finish, :distance, :duration, :gas_stations, :mpg
	
	def initialize(name, start_place, finish_place, mpg)
		@name = name
		@start = start_place
		@finish = finish_place
		@mpg = mpg.to_f
		@gas_stations =[]
		self.get_distance_duration
    	self.get_gas_stations
	end

	def gas_price
		(@distance.gsub(",", "").to_f / @mpg) * self.return_cheapest_or_closest_gas_stations.first.price.to_f
	end

	
	def get_places_interest
		finish_lat = self.finish.latitude.to_s
		finish_lon = self.finish.longitude.to_s

		google_key = ENV['GOOGLE_DIRECTION_MATRIX_APIKEY']

	 	url ="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{finish_lat},#{finish_lon}&radius=50000&types=campground|rv_park&key=#{google_key}"

		response = JSON.load(RestClient.get(url))
	 	
		response["rows"][0]["elements"].map do |f|
			@distance = f["distance"]["text"]
		    @duration= f["duration"]["text"]
			end

	end


	def get_distance_duration
		google_key = ENV['GOOGLE_DIRECTION_MATRIX_APIKEY']
		
		origin = self.start.address
		dest = self.finish.address

	
		url ="https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{origin}&destinations=#{dest}&units=imperial&language=en-EN&key=#{google_key}"

	 	response = JSON.load(RestClient.get(url))
	 	# p "this is the response "
	 	# p  response
	 	# p "END"
	 	#  #p["rows"][0]["elements"][0]["status"]
					
		response["rows"][0]["elements"].map do |f|	
			@distance = f["distance"]["text"]
		    @duration= f["duration"]["text"]   
		end
	 end

	 def get_gas_stations
		start_lat = self.start.latitude.to_s
		start_lon = self.start.longitude.to_s
		gas_key = ENV['GASFEED_APIKEY']
		url = "http://api.mygasfeed.com/stations/radius/#{start_lat}/#{start_lon}/5/reg/price/#{gas_key}.json"

	 	response = JSON.load(RestClient.get(url))
		response["stations"].each do |f|
			price = f["reg_price"]
			name = f["station"]
			city = f["city"]
			distance = f["distance"]
			address = f["address"]
			self.gas_stations << GasStation.new(name, price, city, distance, address)
		 end
	 end


	 # return the GasStations with the lowest price
	 # or the closest station
	 def return_cheapest_or_closest_gas_stations
	 	cheapest = []
	 	closest = []
	 	self.gas_stations.each do |station|
	 		if closest.empty?
 				closest.push(station)
 			else
 				closest = [station] if station.distance.to_f < closest.first.distance.to_f
 			end 
	 		unless station.price == "N/A"
	 			if cheapest.empty?
	 				cheapest.push(station)
	 			else
	 				if station.price.to_f < cheapest.first.price.to_f
	 					cheapest = [station]
	 				elsif station.price.to_f == cheapest.first.price.to_f
	 					cheapest << station
	 				end
	 			end 
	 		end 
	 	end
	 	cheapest.empty? ? closest : cheapest 
	 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  def new

  end
 
  def show
  	#get parameters from form for a Trip
    start_place = Place.new(params[:start_address])
    end_place = Place.new(params[:end_address])
    
   
    #create Trip object
    @trip = Trip.new(params[:name], start_place, end_place, params[:mpg])
    
    #call Trip methods
    # @trips=[]

    # @trips<<@trip
   
    # @hash = Gmaps4rails.build_markers(@trips) do |trip, marker|
    #   marker.lat trip.start.latitude
    #   marker.lng trip.start.longitude

    #   marker.lat trip.finish.latitude
    #   marker.lng trip.finish.longitude
    # end
    end 



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Displaying text directions with <code>setPanel()</code></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-trubolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  
  <body>
    
    <header>
      <a href="/"><%= image_tag("logo.png",id: "logo") %></a><h1 id="title"><span id="trip" >Fuel</span> MyTrip!</h1>

    </header>
   		

      <%=yield%>
     
  </body>
</html>

app/views/trips/new.html.erb
<div class="form_class">
	<h1>New Trip</h1>
 	<%= form_tag(trips_show_path, method: :get,) do %>

		<p><%= text_field_tag :name, nil, placeholder: "name" %></p>
	
		<p><%= text_field_tag :start_address, nil, placeholder: "start", id: "start"%></p>
		<p><%= text_field_tag :end_address, nil, placeholder: "end", id: "end" %></p>
		
		<p><%= text_field_tag :mpg, nil, placeholder: "Miles Per Gallon" %></p>
	
		<p ><%= submit_tag "Trip it!",class: :form_button %></p>
	<%end%>
</div>
<div id="map-canvas"></div>

app/views/trips/show.html.erb
		
		 <div id="map-canvas"> 
			
		 </div>
		 
		 <div id="control"> </div>
		 
		 <div id="directions-panel"> </div>

		<div id="trip-stats">
			<h3 id="trip-name"><%= @trip.name.capitalize%></h3>
			<ul id="trip-link">
				<li class="trip-list"><strong>Gas Cost:</strong> <%= number_to_currency(@trip.gas_price) %></li>
				<li class="trip-list" ><strong>Distance: </strong><%= @trip.distance %></li>
				<li class="trip-list"><strong>Duration:</strong> <%= @trip.duration %></li>
			</ul>
		</div>

		<div id="cheapest-station">
				<h3 id="station-name"> Cheapest Station around <%= @trip.start.address.capitalize %></h3>
				<ul id="station-link">
				<% @trip.return_cheapest_or_closest_gas_stations.each do |station| %>
					<li> Name: <%= station.name %> <li>
						<li>Address:<%= station.address %> </li>
						<li>Price: <%= number_to_currency(station.price) %> </li>
						<li> Distance: <%= station.distance %> </li>
				<% end %>
				</ul>
		</div>
		
	
<script type="text/javascript">
	var tripDetails = {start_lat: <%= @trip.start.latitude %>, start_lon: <%= @trip.start.longitude %>, start_address: '<%= @trip.start.address %>', finish_address: '<%= @trip.finish.address %>' };
</script>
	